### ISSUE TITLE
difference to configparser

### ISSUE THREAD

**Issue by buhtz** [xflr6/fileconfig#1]
I read the doc of course.
But I can not see a big difference between "fileconfig" and the Python-own "configparser".

Can you explain the diff?

**Comment by xflr6** [comment]
Sure, `fileconfig` uses `ConfigParser` from the stdlib under the hood (though you can override that). The latter provides config file parsing with a basic `get(section, option)` API, while `fileconfig` builds upon that to providing an API for a more specialized use case: config file sections as singleton instances of a user-defined class, aliasing, inheritance, and overlay of build-in and user-provided config.

Say, you write an app for running/automating specific tasks. Each task is defined by a config file section. Some tasks are build-in, and users can add their own by putting them in their config file. For you as an app writer this will be only a few lines of a `fileconfig.Stacked` subclass definition containing your buissness logic and a config file residing inside your package directory. Loading user config files boils down to `YourClass.add(<filename>)`. All the logic to make that possible (e.g. resolving paths relative to currently executed file) is done in the background by the `fileconfig` package.

I extracted this functionality from an earlier draft of the `features` package as it looked to me like a logical chunk of one separatable functionality that might be reusable later/by others. Even if there would never be a case for reusing, it seems easier to test and refine a nicely moduarlized piece of software than a bigger monolitic block.

**Comment by buhtz** [comment]
What is about writing the config file back? How did I do that?

And how can I keep the comment-lines (# or ;) from the original file?

**Comment by xflr6** [comment]
I am not so sure that you use the package for what it was designed, but you can of course add a `save()`-method to your subclass using `ConfigParser` with the `filename` and `key` attributes to identify the file and section to update.

Ignoring comment-lines is `ConfigParser` behaviour, so technically you need to override  `_parser` with a different class that does what you want. However, this might conflict with the basic idea that config files consist of key-value pairs (though you could create keys like `comment0`, `comment1` etc.) and therefore turn out as a bad idea in the end.
